run:
  skip-dirs:
    - mocks
    - docs

linters:
  enable-all: true
  disable:
    - maligned
    - wsl
    - whitespace
    - godox
    - godot
    - interfacer
    - nolintlint
    - noctx
    - gofumpt
    - exhaustive
    - gci
    - nlreturn
    - exhaustivestruct
    - forbidigo
    - paralleltest
    - cyclop # we already have gocyclo enabled
    - ifshort
    - nilerr
    - thelper
    - tagliatelle
    - golint # deprecated in favour of revive
    - scopelint # deprecated in favour of exportloopref
    - revive
    - ireturn
    - nonamedreturns
    - exhaustruct
    - gomnd
    - varnamelen
    - varcheck # deprecated in favour of unused
    - deadcode # deprecated in favour of unused
    - structcheck # deprecated in favour of unused
    - nosnakecase # deprecated in favour of revive
    - musttag

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  new-from-rev: HEAD~
  exclude:
    - "should have a package comment, unless it's in another file for this package"
    - "(struct field|var|func|method|func parameter|range var|const|type) .* should be .*"
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - scopelint
        - dupl
        - stylecheck
        - funlen
        - lll
    - path: stub
      linters:
        - funlen
    - path: api
      linters:
        - dupl

    # https://github.com/go-critic/go-critic/issues/926
    - linters:
        - gocritic
      text: "unnecessaryDefer:"
    - linters:
        - lll
      source: "^//go:generate "
